# Generated by Django 2.2.7 on 2019-11-30 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registerForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10)),
                ('user_nickname', models.CharField(max_length=5)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='F', max_length=1)),
                ('phone_num', models.CharField(max_length=11)),
                ('studentCard_image', models.ImageField(upload_to='auth')),
                ('university_auth', models.BooleanField(default=False)),
                ('desired_gender_ratio', models.IntegerField(verbose_name='희망 성비')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TempUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10)),
                ('user_nickname', models.CharField(max_length=5)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='F', max_length=1)),
                ('phone_num', models.CharField(max_length=11)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.University')),
            ],
        ),
    ]
