# Generated by Django 2.2.5 on 2019-10-31 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('university', models.CharField(max_length=1)),
                ('major', models.CharField(max_length=30)),
                ('rooms', models.ManyToManyField(to='main.Room')),
            ],
        ),
    ]
