# Generated by Django 2.2.5 on 2019-11-01 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='simpleuser',
            name='rooms',
        ),
        migrations.AddField(
            model_name='simpleuser',
            name='self_pr',
            field=models.CharField(default='#이런사람', max_length=50),
        ),
        migrations.AddField(
            model_name='simpleuser',
            name='sex',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='major',
            field=models.CharField(default='전공미입력', max_length=50),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.University'),
        ),
    ]
