# Generated by Django 2.2.7 on 2019-11-30 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerform',
            name='desired_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.RoomCandidate'),
        ),
        migrations.AddField(
            model_name='registerform',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.University'),
        ),
    ]
