# Generated by Django 2.2.7 on 2019-12-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191204_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcardimage',
            name='username',
            field=models.CharField(default='name', max_length=20),
        ),
    ]
