# Generated by Django 2.2.5 on 2019-11-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191101_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleuser',
            name='user_nickname',
            field=models.CharField(default='nickname', max_length=15, unique=True),
        ),
    ]
