# Generated by Django 2.2.7 on 2019-12-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_username_in_StudentCardImage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerform',
            name='studentCard_image',
            field=models.ImageField(upload_to='auth/%Y/%m/%d'),
        ),
        migrations.DeleteModel(
            name='StudentCardImage',
        ),
    ]
