# Generated by Django 2.2.7 on 2019-11-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191115_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='school_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_nickname',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
