# Generated by Django 3.0 on 2019-12-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_StudentCardImage'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerform',
            name='is_photoOK',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tempuser',
            name='is_photoOK',
            field=models.IntegerField(default=0),
        ),
    ]
