# Generated by Django 2.2.5 on 2019-11-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191103_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleuser',
            name='user_nickname',
            field=models.CharField(max_length=15),
        ),
    ]
