# Generated by Django 2.2.5 on 2019-10-31 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_master', models.CharField(max_length=15)),
                ('activity', models.CharField(max_length=1)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('total_number_of_user', models.IntegerField()),
                ('sex_ratio', models.IntegerField(default=0)),
                ('room_name', models.TextField(default='반갑습니다~', max_length=100)),
                ('is_Confirm', models.BooleanField(default=False)),
            ],
        ),
    ]
