# Generated by Django 2.2.7 on 2019-12-01 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='액티비티 종류')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RoomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.TempUser')),
            ],
        ),
        migrations.CreateModel(
            name='RoomCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Activity')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='members',
            field=models.ManyToManyField(through='main.RoomUser', to='accounts.TempUser'),
        ),
        migrations.AddField(
            model_name='room',
            name='roomCandidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.RoomCandidate'),
        ),
    ]
