# Generated by Django 2.2.5 on 2019-11-01 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191101_1900'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='액티비티 종류')),
            ],
        ),
        migrations.RenameField(
            model_name='room',
            old_name='total_number_of_user',
            new_name='total_number_of_members',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_master',
        ),
        migrations.AlterField(
            model_name='room',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Activity'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(default='반갑습니다~', max_length=100),
        ),
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_nickname', models.CharField(max_length=15)),
                ('is_master', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.SimpleUser')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='members',
            field=models.ManyToManyField(through='main.Join', to='accounts.SimpleUser'),
        ),
    ]
