# Generated by Django 2.2.7 on 2019-11-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(default='액티비티 같이 해요~!', max_length=12),
        ),
    ]
