# Generated by Django 2.2.5 on 2019-11-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191102_0110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['time']},
        ),
        migrations.RemoveField(
            model_name='join',
            name='user_nickname',
        ),
        migrations.AddField(
            model_name='room',
            name='place',
            field=models.CharField(default='활동 장소', max_length=100),
        ),
    ]
