# Generated by Django 2.2.5 on 2019-11-03 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191103_0020'),
        ('main', '0004_auto_20191103_0008'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Join',
            new_name='RoomUser',
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['date', 'time']},
        ),
    ]
